language: node_js
node_js:
  - "0.10"
addons:
  firefox: "31.0" # 3.4->31.0
os:
  - linux
before_install:
  # ROS deps for examples
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install ros-hydro-ros-base
  # temp local install of tf2_web_republisher
  # - sudo apt-get install ros-hydro-rosbridge-server ros-hydro-tf2-web-republisher ros-hydro-common-tutorials ros-hydro-rospy-tutorials ros-hydro-actionlib-tutorials
  - sudo apt-get install ros-hydro-rosbridge-server ros-hydro-common-tutorials ros-hydro-rospy-tutorials ros-hydro-actionlib-tutorials
  - sudo apt-get install python-catkin-pkg python-rosdep ros-hydro-catkin -qq
  - sudo rosdep init
  - rosdep update
  - mkdir -p /tmp/ws/src
  - ln -s `pwd` /tmp/ws/roslibjs
  - cd /tmp/ws/src
  - git clone https://github.com/RobotWebTools/tf2_web_republisher.git
  - cd ../
  - rosdep install --from-paths src --ignore-src --rosdistro hydro -y
  - cd /tmp/ws/roslibjs
  - npm install -g grunt-cli karma-cli

  # Set up Xfvb for Firefox headless testing
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - source /opt/ros/hydro/setup.bash
  - cd /tmp/ws
  - catkin_make
  - catkin_make install
  - source install/setup.bash
  - cd /tmp/ws/roslibjs
  - sh test/examples/setup_examples.sh
script:
  - rostopic list
  - npm test
  - npm run test-examples
